- hosts: localhost
  become: true
  tasks:
  - name: Install htop
    dnf: name={{item}}
      - htop
      - mc
      - tmux
      - ffmpeg
      - vim
      - nodejs
      - keepassxc
      - brightnessctl 
