- name: Install python-psutil package
  dnf: name=python-psutil
- name: Install arc theme
  dnf: name=arc-theme

- name: Copy wallpaper file
  copy: src=files/wallpapers/wallpaper.jpg dest=/home/reedmcfadden/.wallpaper.jpg owner=reedmcfadden group=reedmcfadden mode=600

- name: Set GNOME Wallpaper
  become_user: reedmcfadden
    # TODO - don't copy file to ~/.wallpaper.jpg... just copy it to pictures
    # and use that
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/reedmcfadden/.wallpaper.jpg'"

- name: Copy lockscreenfile
    # TODO - don't copy file to as a dotfile in home dir... just copy it to pictures
    # and use that
  copy: src=files/wallpapers/lockscreen.jpg dest=/home/reedmcfadden/.lockscreen.jpg owner=reedmcfadden group=reedmcfadden mode=600

- name: Set lock screen background
  become_user: reedmcfadden
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/reedmcfadden/.lockscreen.jpg'"

- name: Set GTK theme
  become_user: reedmcfadden
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Arc'"

- name: Set switch to workspace 'X' keybinds
  become_user: reedmcfadden
  dconf: 
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items: 
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1", value: "['<Alt>1']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2", value: "['<Alt>2']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3", value: "['<Alt>3']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4", value: "['<Alt>4']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5", value: "['<Alt>5']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6", value: "['<Alt>6']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7", value: "['<Alt>7']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8", value: "['<Alt>8']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9", value: "['<Alt>9']" }
    - { key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-10", value: "['<Alt>0']" }

- name: Set move to workspace 'X' keybinds
  become_user: reedmcfadden
  dconf: 
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items: 
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-1", value: "['<Shift><Alt>1']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-2", value: "['<Shift><Alt>2']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-3", value: "['<Shift><Alt>3']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-4", value: "['<Shift><Alt>4']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-5", value: "['<Shift><Alt>5']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-6", value: "['<Shift><Alt>6']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-7", value: "['<Shift><Alt>7']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-8", value: "['<Shift><Alt>8']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-9", value: "['<Shift><Alt>9']" }
    - { key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-10", value: "['<Shift><Alt>0']" }

- name: Turn off gnome automate update downloads (eats a lot of CPU)
  become_user: reedmcfadden
  dconf: "key=/org/gnome/software/download-updates value=false"


