- name: Install htop
  dnf: 
  name: "{{ item }}"
    # TODO - split out packages into 'functional units' (ex: setup desktop,
    # cpp development, video, gaming, etc.)
  loop:
    - htop
    - tmux
    - ffmpeg-free
    - vim
    - nodejs
    - keepassxc
    - cronie
    - cronie-anacron
    - virt-manager

    # TODO - automate vscode Install
    # sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
    # sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    # sudo dnf update
    # sudo dnf install code -y
    #
    # TODO - automate dropbox install
    # cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
    # ~/.dropbox-dist/dropboxd
