- name: Install htop
  dnf: 
    name: "{{ item }}"
  loop:
    - htop
    - tmux
    - ffmpeg
    - vim
    - nodejs
    - keepassxc
    - brightnessctl 
    - cronie
    - cronie-anacron
    - kitty
 
# TODO - split out packages into 'functional units'
